<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260716120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create SchoolPay core tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(120) NOT NULL, last_name VARCHAR(120) NOT NULL, phone VARCHAR(40) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON "user" (email)');
        $this->addSql('CREATE TABLE school_year (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(30) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, is_active BOOLEAN NOT NULL, is_closed BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_school_year_name ON school_year (name)');
        $this->addSql('CREATE TABLE school_class (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, school_year_id INT NOT NULL, name VARCHAR(80) NOT NULL, level VARCHAR(80) NOT NULL, description TEXT DEFAULT NULL, capacity INT DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CLASS_YEAR ON school_class (school_year_id)');
        $this->addSql('CREATE INDEX idx_class_level ON school_class (level)');
        $this->addSql('CREATE TABLE parent_guardian (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT DEFAULT NULL, first_name VARCHAR(120) NOT NULL, last_name VARCHAR(120) NOT NULL, email VARCHAR(180) DEFAULT NULL, phone VARCHAR(40) NOT NULL, alternate_phone VARCHAR(40) DEFAULT NULL, address TEXT DEFAULT NULL, profession VARCHAR(120) DEFAULT NULL, relationship_type VARCHAR(60) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PARENT_USER ON parent_guardian (user_id)');
        $this->addSql('CREATE INDEX idx_parent_email ON parent_guardian (email)');
        $this->addSql('CREATE TABLE student (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, school_class_id INT NOT NULL, school_year_id INT NOT NULL, registration_number VARCHAR(50) NOT NULL, first_name VARCHAR(120) NOT NULL, last_name VARCHAR(120) NOT NULL, gender VARCHAR(20) NOT NULL, birth_date DATE DEFAULT NULL, birth_place VARCHAR(120) DEFAULT NULL, address TEXT DEFAULT NULL, photo VARCHAR(255) DEFAULT NULL, status VARCHAR(40) NOT NULL, enrollment_date DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_student_registration ON student (registration_number)');
        $this->addSql('CREATE INDEX IDX_STUDENT_CLASS ON student (school_class_id)');
        $this->addSql('CREATE INDEX IDX_STUDENT_YEAR ON student (school_year_id)');
        $this->addSql('CREATE INDEX idx_student_name ON student (last_name, first_name)');
        $this->addSql('CREATE INDEX idx_student_status ON student (status)');
        $this->addSql('CREATE TABLE student_parent_guardian (student_id INT NOT NULL, parent_guardian_id INT NOT NULL, PRIMARY KEY(student_id, parent_guardian_id))');
        $this->addSql('CREATE INDEX IDX_STUDENT_PARENT_STUDENT ON student_parent_guardian (student_id)');
        $this->addSql('CREATE INDEX IDX_STUDENT_PARENT_PARENT ON student_parent_guardian (parent_guardian_id)');
        $this->addSql('CREATE TABLE fee_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, code VARCHAR(40) NOT NULL, description TEXT DEFAULT NULL, is_mandatory BOOLEAN NOT NULL, is_recurring BOOLEAN NOT NULL, recurrence_type VARCHAR(40) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_fee_type_code ON fee_type (code)');
        $this->addSql('CREATE TABLE fee_assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fee_type_id INT NOT NULL, school_year_id INT NOT NULL, school_class_id INT DEFAULT NULL, student_id INT DEFAULT NULL, amount NUMERIC(12, 2) NOT NULL, due_date DATE NOT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, month_number INT DEFAULT NULL, is_mandatory BOOLEAN NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FEE_TYPE ON fee_assignment (fee_type_id)');
        $this->addSql('CREATE INDEX IDX_FEE_YEAR ON fee_assignment (school_year_id)');
        $this->addSql('CREATE INDEX IDX_FEE_CLASS ON fee_assignment (school_class_id)');
        $this->addSql('CREATE INDEX IDX_FEE_STUDENT ON fee_assignment (student_id)');
        $this->addSql('CREATE INDEX idx_fee_due_date ON fee_assignment (due_date)');
        $this->addSql('CREATE TABLE discount (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, type VARCHAR(20) NOT NULL, value NUMERIC(12, 2) NOT NULL, reason TEXT DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE student_discount (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, student_id INT NOT NULL, discount_id INT NOT NULL, fee_assignment_id INT DEFAULT NULL, school_year_id INT NOT NULL, approved_by_id INT DEFAULT NULL, justification TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_STUDENT_DISCOUNT_STUDENT ON student_discount (student_id)');
        $this->addSql('CREATE INDEX IDX_STUDENT_DISCOUNT_DISCOUNT ON student_discount (discount_id)');
        $this->addSql('CREATE INDEX IDX_STUDENT_DISCOUNT_FEE ON student_discount (fee_assignment_id)');
        $this->addSql('CREATE INDEX IDX_STUDENT_DISCOUNT_YEAR ON student_discount (school_year_id)');
        $this->addSql('CREATE INDEX IDX_STUDENT_DISCOUNT_APPROVED ON student_discount (approved_by_id)');
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, student_id INT NOT NULL, school_year_id INT NOT NULL, received_by_id INT DEFAULT NULL, cancelled_by_id INT DEFAULT NULL, payment_number VARCHAR(60) NOT NULL, payment_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, total_amount NUMERIC(12, 2) NOT NULL, payment_method VARCHAR(40) NOT NULL, external_reference VARCHAR(120) DEFAULT NULL, status VARCHAR(40) NOT NULL, notes TEXT DEFAULT NULL, cancellation_reason TEXT DEFAULT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_payment_number ON payment (payment_number)');
        $this->addSql('CREATE INDEX IDX_PAYMENT_STUDENT ON payment (student_id)');
        $this->addSql('CREATE INDEX IDX_PAYMENT_YEAR ON payment (school_year_id)');
        $this->addSql('CREATE INDEX IDX_PAYMENT_RECEIVED ON payment (received_by_id)');
        $this->addSql('CREATE INDEX IDX_PAYMENT_CANCELLED ON payment (cancelled_by_id)');
        $this->addSql('CREATE INDEX idx_payment_date ON payment (payment_date)');
        $this->addSql('CREATE INDEX idx_payment_status ON payment (status)');
        $this->addSql('CREATE TABLE payment_detail (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, payment_id INT NOT NULL, fee_assignment_id INT NOT NULL, amount NUMERIC(12, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_PAYMENT_DETAIL_PAYMENT ON payment_detail (payment_id)');
        $this->addSql('CREATE INDEX IDX_PAYMENT_DETAIL_FEE ON payment_detail (fee_assignment_id)');
        $this->addSql('CREATE TABLE receipt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, payment_id INT NOT NULL, receipt_number VARCHAR(60) NOT NULL, generated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, file_path VARCHAR(255) DEFAULT NULL, verification_code VARCHAR(80) NOT NULL, qr_code_data TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_RECEIPT_PAYMENT ON receipt (payment_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_receipt_number ON receipt (receipt_number)');
        $this->addSql('CREATE UNIQUE INDEX uniq_receipt_verification ON receipt (verification_code)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, title VARCHAR(160) NOT NULL, message TEXT NOT NULL, type VARCHAR(40) NOT NULL, is_read BOOLEAN NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_NOTIFICATION_USER ON notification (user_id)');
        $this->addSql('CREATE TABLE audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT DEFAULT NULL, action VARCHAR(80) NOT NULL, entity_type VARCHAR(120) NOT NULL, entity_id INT DEFAULT NULL, description TEXT NOT NULL, old_values JSON DEFAULT NULL, new_values JSON DEFAULT NULL, ip_address VARCHAR(80) DEFAULT NULL, user_agent TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AUDIT_USER ON audit_log (user_id)');
        $this->addSql('CREATE INDEX idx_audit_action ON audit_log (action)');
        $this->addSql('CREATE INDEX idx_audit_entity_type ON audit_log (entity_type)');
        $this->addSql('CREATE INDEX idx_audit_created_at ON audit_log (created_at)');
        $this->addSql('CREATE TABLE school_setting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, school_name VARCHAR(160) NOT NULL, school_code VARCHAR(40) NOT NULL, address TEXT DEFAULT NULL, phone VARCHAR(40) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, currency VARCHAR(40) NOT NULL, currency_symbol VARCHAR(12) NOT NULL, receipt_footer TEXT DEFAULT NULL, default_payment_deadline INT NOT NULL, late_fee_enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');

        $this->addSql('ALTER TABLE school_class ADD CONSTRAINT FK_CLASS_YEAR FOREIGN KEY (school_year_id) REFERENCES school_year (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parent_guardian ADD CONSTRAINT FK_PARENT_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_STUDENT_CLASS FOREIGN KEY (school_class_id) REFERENCES school_class (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_STUDENT_YEAR FOREIGN KEY (school_year_id) REFERENCES school_year (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_parent_guardian ADD CONSTRAINT FK_STUDENT_PARENT_STUDENT FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_parent_guardian ADD CONSTRAINT FK_STUDENT_PARENT_PARENT FOREIGN KEY (parent_guardian_id) REFERENCES parent_guardian (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fee_assignment ADD CONSTRAINT FK_FEE_TYPE FOREIGN KEY (fee_type_id) REFERENCES fee_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fee_assignment ADD CONSTRAINT FK_FEE_YEAR FOREIGN KEY (school_year_id) REFERENCES school_year (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fee_assignment ADD CONSTRAINT FK_FEE_CLASS FOREIGN KEY (school_class_id) REFERENCES school_class (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fee_assignment ADD CONSTRAINT FK_FEE_STUDENT FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_discount ADD CONSTRAINT FK_SD_STUDENT FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_discount ADD CONSTRAINT FK_SD_DISCOUNT FOREIGN KEY (discount_id) REFERENCES discount (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_discount ADD CONSTRAINT FK_SD_FEE FOREIGN KEY (fee_assignment_id) REFERENCES fee_assignment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_discount ADD CONSTRAINT FK_SD_YEAR FOREIGN KEY (school_year_id) REFERENCES school_year (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_discount ADD CONSTRAINT FK_SD_APPROVED FOREIGN KEY (approved_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_PAYMENT_STUDENT FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_PAYMENT_YEAR FOREIGN KEY (school_year_id) REFERENCES school_year (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_PAYMENT_RECEIVED FOREIGN KEY (received_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_PAYMENT_CANCELLED FOREIGN KEY (cancelled_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_detail ADD CONSTRAINT FK_PD_PAYMENT FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_detail ADD CONSTRAINT FK_PD_FEE FOREIGN KEY (fee_assignment_id) REFERENCES fee_assignment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE receipt ADD CONSTRAINT FK_RECEIPT_PAYMENT FOREIGN KEY (payment_id) REFERENCES payment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_NOTIFICATION_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE audit_log ADD CONSTRAINT FK_AUDIT_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE receipt');
        $this->addSql('DROP TABLE payment_detail');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE student_discount');
        $this->addSql('DROP TABLE discount');
        $this->addSql('DROP TABLE fee_assignment');
        $this->addSql('DROP TABLE fee_type');
        $this->addSql('DROP TABLE student_parent_guardian');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE parent_guardian');
        $this->addSql('DROP TABLE school_class');
        $this->addSql('DROP TABLE school_year');
        $this->addSql('DROP TABLE school_setting');
        $this->addSql('DROP TABLE "user"');
    }
}
